<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Tiendas', 'doctrine');

/**
 * BaseTiendas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idtienda
 * @property integer $idzona
 * @property string $nombretienda
 * @property string $latitud
 * @property string $longitud
 * @property Zonas $Zonas
 * 
 * @method integer getIdtienda()     Returns the current record's "idtienda" value
 * @method integer getIdzona()       Returns the current record's "idzona" value
 * @method string  getNombretienda() Returns the current record's "nombretienda" value
 * @method string  getLatitud()      Returns the current record's "latitud" value
 * @method string  getLongitud()     Returns the current record's "longitud" value
 * @method Zonas   getZonas()        Returns the current record's "Zonas" value
 * @method Tiendas setIdtienda()     Sets the current record's "idtienda" value
 * @method Tiendas setIdzona()       Sets the current record's "idzona" value
 * @method Tiendas setNombretienda() Sets the current record's "nombretienda" value
 * @method Tiendas setLatitud()      Sets the current record's "latitud" value
 * @method Tiendas setLongitud()     Sets the current record's "longitud" value
 * @method Tiendas setZonas()        Sets the current record's "Zonas" value
 * 
 * @package    mant-guia-maestra
 * @subpackage model
 * @author     Rodrigo Campos H. rodrigo <at> webdevel <dot> cl
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTiendas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tiendas');
        $this->hasColumn('idtienda', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idzona', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nombretienda', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('latitud', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('longitud', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Zonas', array(
             'local' => 'idzona',
             'foreign' => 'idzona'));
    }
}