<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Detalleversion', 'doctrine');

/**
 * BaseDetalleversion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $iddetalleversion
 * @property integer $idversion
 * @property float $nropagina
 * @property string $accion
 * @property Version $Version
 * 
 * @method integer        getIddetalleversion() Returns the current record's "iddetalleversion" value
 * @method integer        getIdversion()        Returns the current record's "idversion" value
 * @method float          getNropagina()        Returns the current record's "nropagina" value
 * @method string         getAccion()           Returns the current record's "accion" value
 * @method Version        getVersion()          Returns the current record's "Version" value
 * @method Detalleversion setIddetalleversion() Sets the current record's "iddetalleversion" value
 * @method Detalleversion setIdversion()        Sets the current record's "idversion" value
 * @method Detalleversion setNropagina()        Sets the current record's "nropagina" value
 * @method Detalleversion setAccion()           Sets the current record's "accion" value
 * @method Detalleversion setVersion()          Sets the current record's "Version" value
 * 
 * @package    mant-guia-maestra
 * @subpackage model
 * @author     Rodrigo Campos H. rodrigo <at> webdevel <dot> cl
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDetalleversion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('detalleversion');
        $this->hasColumn('iddetalleversion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('idversion', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nropagina', 'float', 4, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('accion', 'string', 15, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 15,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Version', array(
             'local' => 'idversion',
             'foreign' => 'idversion'));
    }
}