<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Zonas', 'doctrine');

/**
 * BaseZonas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idzona
 * @property string $nombrezona
 * @property Doctrine_Collection $Tiendas
 * 
 * @method integer             getIdzona()     Returns the current record's "idzona" value
 * @method string              getNombrezona() Returns the current record's "nombrezona" value
 * @method Doctrine_Collection getTiendas()    Returns the current record's "Tiendas" collection
 * @method Zonas               setIdzona()     Sets the current record's "idzona" value
 * @method Zonas               setNombrezona() Sets the current record's "nombrezona" value
 * @method Zonas               setTiendas()    Sets the current record's "Tiendas" collection
 * 
 * @package    mant-guia-maestra
 * @subpackage model
 * @author     Rodrigo Campos H. rodrigo <at> webdevel <dot> cl
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseZonas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('zonas');
        $this->hasColumn('idzona', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nombrezona', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 150,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Tiendas', array(
             'local' => 'idzona',
             'foreign' => 'idzona'));
    }
}