<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Subcategoria', 'doctrine');

/**
 * BaseSubcategoria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idsubcategoria
 * @property integer $idcategoria
 * @property string $nombresubcategoria
 * @property integer $paginicio
 * @property integer $pagfin
 * @property Categorias $Categorias
 * @property Doctrine_Collection $Paginas
 * 
 * @method integer             getIdsubcategoria()     Returns the current record's "idsubcategoria" value
 * @method integer             getIdcategoria()        Returns the current record's "idcategoria" value
 * @method string              getNombresubcategoria() Returns the current record's "nombresubcategoria" value
 * @method integer             getPaginicio()          Returns the current record's "paginicio" value
 * @method integer             getPagfin()             Returns the current record's "pagfin" value
 * @method Categorias          getCategorias()         Returns the current record's "Categorias" value
 * @method Doctrine_Collection getPaginas()            Returns the current record's "Paginas" collection
 * @method Subcategoria        setIdsubcategoria()     Sets the current record's "idsubcategoria" value
 * @method Subcategoria        setIdcategoria()        Sets the current record's "idcategoria" value
 * @method Subcategoria        setNombresubcategoria() Sets the current record's "nombresubcategoria" value
 * @method Subcategoria        setPaginicio()          Sets the current record's "paginicio" value
 * @method Subcategoria        setPagfin()             Sets the current record's "pagfin" value
 * @method Subcategoria        setCategorias()         Sets the current record's "Categorias" value
 * @method Subcategoria        setPaginas()            Sets the current record's "Paginas" collection
 * 
 * @package    mant-guia-maestra
 * @subpackage model
 * @author     Rodrigo Campos H. rodrigo <at> webdevel <dot> cl
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSubcategoria extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('subcategoria');
        $this->hasColumn('idsubcategoria', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('idcategoria', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nombresubcategoria', 'string', 150, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 150,
             ));
        $this->hasColumn('paginicio', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('pagfin', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Categorias', array(
             'local' => 'idcategoria',
             'foreign' => 'idcategoria'));

        $this->hasMany('Paginas', array(
             'local' => 'idsubcategoria',
             'foreign' => 'idsubcategoria'));
    }
}