<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Paginas', 'doctrine');

/**
 * BasePaginas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $idpagina
 * @property integer $idsubcategoria
 * @property float $nropagina
 * @property blob $imagenprincipal
 * @property blob $imagenmini
 * @property string $tipopagina
 * @property Subcategoria $Subcategoria
 * 
 * @method integer      getIdpagina()        Returns the current record's "idpagina" value
 * @method integer      getIdsubcategoria()  Returns the current record's "idsubcategoria" value
 * @method float        getNropagina()       Returns the current record's "nropagina" value
 * @method blob         getImagenprincipal() Returns the current record's "imagenprincipal" value
 * @method blob         getImagenmini()      Returns the current record's "imagenmini" value
 * @method string       getTipopagina()      Returns the current record's "tipopagina" value
 * @method Subcategoria getSubcategoria()    Returns the current record's "Subcategoria" value
 * @method Paginas      setIdpagina()        Sets the current record's "idpagina" value
 * @method Paginas      setIdsubcategoria()  Sets the current record's "idsubcategoria" value
 * @method Paginas      setNropagina()       Sets the current record's "nropagina" value
 * @method Paginas      setImagenprincipal() Sets the current record's "imagenprincipal" value
 * @method Paginas      setImagenmini()      Sets the current record's "imagenmini" value
 * @method Paginas      setTipopagina()      Sets the current record's "tipopagina" value
 * @method Paginas      setSubcategoria()    Sets the current record's "Subcategoria" value
 * 
 * @package    mant-guia-maestra
 * @subpackage model
 * @author     Rodrigo Campos H. rodrigo <at> webdevel <dot> cl
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePaginas extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('paginas');
        $this->hasColumn('idpagina', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('idsubcategoria', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nropagina', 'float', 4, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('imagenprincipal', 'blob', null, array(
             'type' => 'blob',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('imagenmini', 'blob', null, array(
             'type' => 'blob',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('tipopagina', 'string', 3, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 3,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Subcategoria', array(
             'local' => 'idsubcategoria',
             'foreign' => 'idsubcategoria'));
    }
}