<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Productopagina', 'doctrine');

/**
 * BaseProductopagina
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $pagina
 * @property string $sku
 * @property integer $tamanofuente
 * @property integer $coorx
 * @property integer $coory
 * @property string $unidad
 * @property integer $comprar
 * @property string $skupadre
 * @property integer $padre
 * @property integer $visible
 * 
 * @method integer        getPagina()       Returns the current record's "pagina" value
 * @method string         getSku()          Returns the current record's "sku" value
 * @method integer        getTamanofuente() Returns the current record's "tamanofuente" value
 * @method integer        getCoorx()        Returns the current record's "coorx" value
 * @method integer        getCoory()        Returns the current record's "coory" value
 * @method string         getUnidad()       Returns the current record's "unidad" value
 * @method integer        getComprar()      Returns the current record's "comprar" value
 * @method string         getSkupadre()     Returns the current record's "skupadre" value
 * @method integer        getPadre()        Returns the current record's "padre" value
 * @method integer        getVisible()      Returns the current record's "visible" value
 * @method Productopagina setPagina()       Sets the current record's "pagina" value
 * @method Productopagina setSku()          Sets the current record's "sku" value
 * @method Productopagina setTamanofuente() Sets the current record's "tamanofuente" value
 * @method Productopagina setCoorx()        Sets the current record's "coorx" value
 * @method Productopagina setCoory()        Sets the current record's "coory" value
 * @method Productopagina setUnidad()       Sets the current record's "unidad" value
 * @method Productopagina setComprar()      Sets the current record's "comprar" value
 * @method Productopagina setSkupadre()     Sets the current record's "skupadre" value
 * @method Productopagina setPadre()        Sets the current record's "padre" value
 * @method Productopagina setVisible()      Sets the current record's "visible" value
 * 
 * @package    mant-guia-maestra
 * @subpackage model
 * @author     Rodrigo Campos H. rodrigo <at> webdevel <dot> cl
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductopagina extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('productopagina');
        $this->hasColumn('pagina', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('sku', 'string', 7, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 7,
             ));
        $this->hasColumn('tamanofuente', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('coorx', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('coory', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('unidad', 'string', 10, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('comprar', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('skupadre', 'string', 7, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 7,
             ));
        $this->hasColumn('padre', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('visible', 'integer', null, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'default' => 1,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}