<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/09/23 13:38:01
sfConfig::add(array(
  'app_sf_guard_plugin_remember_key_expiration_age' => 1800,
  'app_sf_guard_plugin_remember_cookie_name' => 'GuiaMaestraSodimac',
  'app_sf_guard_plugin_success_signout_url' => 'homepage',
));
