<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/09/23 13:38:17
$this->security = array (
  'new' => 
  array (
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'super-admin',
        1 => 'admin',
      ),
    ),
  ),
  'create' => 
  array (
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'super-admin',
        1 => 'admin',
      ),
    ),
  ),
  'edit' => 
  array (
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'super-admin',
        1 => 'admin',
      ),
    ),
  ),
  'update' => 
  array (
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'super-admin',
        1 => 'admin',
      ),
    ),
  ),
  'delete' => 
  array (
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'super-admin',
        1 => 'admin',
      ),
    ),
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
