<?php
// auto-generated by sfViewConfigHandler
// date: 2013/09/23 13:38:13
$response = $this->context->getResponse();

if ($this->actionName.$this->viewName == 'signinSuccess')
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}
else
{
  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());
}

if ($templateName.$this->viewName == 'signinSuccess')
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else
  {
    $this->setDecoratorTemplate('' == 'sfGuardAuthLayout' ? false : 'sfGuardAuthLayout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Sodimac - Guia Maestra', false, false);
  $response->addMeta('language', 'es', false, false);

  $response->addStylesheet('bootstrap.min.css', '', array ());
  $response->addStylesheet('bootstrap-theme.min.css', '', array ());
  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('signin.css', '', array ());
  $response->addJavascript('jquery.js', '', array ());
  $response->addJavascript('html5shiv.js', '', array (  'condition' => 'lt IE 9',));
  $response->addJavascript('respond.min.js', '', array (  'condition' => 'lt IE 9',));
  $response->addJavascript('bootstrap.min.js', '', array ());
}
else
{
  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', 'Sodimac - Guia Maestra', false, false);
  $response->addMeta('language', 'es', false, false);

  $response->addStylesheet('bootstrap.min.css', '', array ());
  $response->addStylesheet('bootstrap-theme.min.css', '', array ());
  $response->addStylesheet('main.css', '', array ());
  $response->addJavascript('jquery.js', '', array ());
  $response->addJavascript('html5shiv.js', '', array (  'condition' => 'lt IE 9',));
  $response->addJavascript('respond.min.js', '', array (  'condition' => 'lt IE 9',));
  $response->addJavascript('bootstrap.min.js', '', array ());
}

