<?php

/**
 * DetalleversionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DetalleversionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DetalleversionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Detalleversion');
    }
}