<?php

/**
 * Paginas
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    mant-guia-maestra
 * @subpackage model
 * @author     Rodrigo Campos H. rodrigo <at> webdevel <dot> cl
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Paginas extends BasePaginas
{
  public function save(Doctrine_Connection $conn = null)
  {
    if ($this->isNew())
    {
      $nroPaginaActual = $this->getNropagina();

      $ultimasPaginas = Doctrine_Core::getTable('Paginas')
                            ->createQuery('a')
                            ->where('nropagina >= ?', $nroPaginaActual)
                            ->andWhere('nropagina <= ?', $nroPaginaActual + 1)
                            ->orderBy('nropagina DESC')
                            ->limit(1)
                            ->execute();

      $ultimaPagina = $ultimasPaginas->getFirst()->getNropagina();

      $this->setNropagina($ultimaPagina + 0.1);

    }
 
    return parent::save($conn);
  }
}
