<?php

/**
 * ProductopaginaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductopaginaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductopaginaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Productopagina');
    }
}