<?php

/**
 * ProductopaginaDosTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductopaginaDosTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductopaginaDosTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductopaginaDos');
    }
}