<?php

/**
 * TiendasTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TiendasTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TiendasTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tiendas');
    }
}