<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/09/23 13:57:02

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=guia_maestra_desa',
  'username' => 'sodimac',
  'password' => 'sodimac',
  'name' => 'doctrine',
)),);
